#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('GRAPHQLGEN_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('GRAPHQLGEN_COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );

    die(1);
}

require GRAPHQLGEN_COMPOSER_INSTALL;

use GraphQLGen\Old\Commands\DescribeCommand;
use GraphQLGen\Old\Commands\GenerateClassesCommand;
use Symfony\Component\Console\Application;

$cli = new Application();
$cli->add(new \GraphQLGen\MainCommand());
$cli->run();
