#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use GraphQLGen\Commands\DescribeCommand;
use GraphQLGen\Commands\GenerateClassesCommand;
use Symfony\Component\Console\Application;

$cli = new Application();
$cli->add(new GenerateClassesCommand());
$cli->run();
